### ISSUE TITLE
[Feature] More button on Controller

### ISSUE THREAD

**Issue by parkleo121212** [Kyle-Ye/Video-Speed-Controller#1]
**Is your feature request related to a problem? Please describe.**

![image](https://user-images.githubusercontent.com/72724576/135748538-8624608b-89bd-45dc-8345-1498923a9ef8.png)

On this photo, there are 5 button on the controller which have 5 action, and do the same thing with the keyboard shortcut.
So, what I want is to add one mor button which have action to quickly chang between Normal speed and Prefferred speed, which the "R" kerboard shortcut have it.

**Describe the solution you'd like**
..

**Describe alternatives you've considered**
.

**Additional context**
https://www.clien.net/service/board/cm_iphonien/16556275?od=T31&po=0&category=0&groupCd=clien_all
The link above is the introduction of your extension, with Korean. I wrote it with Korean on Korean biggest IT wabsite, cause I'm Korean :D
And also, I was using this extension on my pc with speed over 3, so I thing it's a bug on iOS version. Thanks.

**Comment by Kyle-Ye** [comment]
First, thank you for sharing this extension, and if user request or you'd like to help, we could add Korean Localization.

Second, I test x2.5 speed on Chrome(Mac), Safari(Mac), Safari(iPad) about this youtube video https://www.youtube.com/watch?v=VT5oZndzj68&list=PLjEaoINr3zgHs8uzT3yqe4iHGfkCmMJ0P&index=2. And they all seem play properly. Can you please add more info in a bug report issue about it? (Like which video you can reproduce this bug)

Third, the feature you request is great, I will implement it soon, and I'll update the progress here in this issue.

**Comment by Kyle-Ye** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> ![image](https://user-images.githubusercontent.com/72724576/135748538-8624608b-89bd-45dc-8345-1498923a9ef8.png)
> 
> On this photo, there are 5 button on the controller which have 5 action, and do the same thing with the keyboard shortcut. So, what I want is to add one mor button which have action to quickly chang between Normal speed and Prefferred speed, which the "R" kerboard shortcut have it.
> 
> **Describe the solution you'd like** ..
> 
> **Describe alternatives you've considered** .
> 
> **Additional context** https://www.clien.net/service/board/cm_iphonien/16556275?od=T31&po=0&category=0&groupCd=clien_all The link above is the introduction of your extension, with Korean. I wrote it with Korean on Korean biggest IT wabsite, cause I'm Korean :D And also, I was using this extension on my pc with speed over 3, so I thing it's a bug on iOS version. Thanks.

The feature you request is already implemented, and the default key is G, I'll add a preferred button on the controller as you suggest

**Comment by Kyle-Ye** [comment]
Which text seems acceptable for you? Is a "love emoji"-🧡 OK?

<img width="212" alt="截屏2021-10-03 18 37 47" src="https://user-images.githubusercontent.com/43724855/135749997-d8760c4f-a45d-4547-a6eb-af6ffb7af19a.png">

**Comment by parkleo121212** [comment]
> Which text seems acceptable for you? Is a "love emoji"-🧡 OK?
> 
> <img alt="截屏2021-10-03 18 37 47" width="212" src="https://user-images.githubusercontent.com/43724855/135749997-d8760c4f-a45d-4547-a6eb-af6ffb7af19a.png">

Cool! 😂 But I was thinking about using SF symbols 3 to increase coherence with iOS. thank you!

**Comment by parkleo121212** [comment]
> > Which text seems acceptable for you? Is a "love emoji"-🧡 OK?
> > <img alt="截屏2021-10-03 18 37 47" width="212" src="https://user-images.githubusercontent.com/43724855/135749997-d8760c4f-a45d-4547-a6eb-af6ffb7af19a.png">
> 
> Cool! 😂 But I was thinking about using SF symbols 3 to increase coherence with iOS. thank you!

speedometer, gobackward, goforward (which is the name of the symbol on SF symbol) will look awesome with action
Prefferred Speed(G), Rewind(Z), and Advance(X)

**Comment by Kyle-Ye** [comment]
> > > Which text seems acceptable for you? Is a "love emoji"-🧡 OK?
> > > <img alt="截屏2021-10-03 18 37 47" width="212" src="https://user-images.githubusercontent.com/43724855/135749997-d8760c4f-a45d-4547-a6eb-af6ffb7af19a.png">
> > 
> > 
> > Cool! 😂 But I was thinking about using SF symbols 3 to increase coherence with iOS. thank you!
> 
> speedometer, gobackward, goforward (which is the name of the symbol on SF symbol) will look awesome with action Prefferred Speed(G), Rewind(Z), and Advance(X)

I am also a big fan of SF Symbol, but this is technically impossible now. Because SF Symbol can only used in Native App(Through UIKit's UIImage or SwiftUI's Image). And the speed controller is just some html which only allow for some char or emoji

**Comment by Kyle-Ye** [comment]
https://stackoverflow.com/questions/64083993/is-there-a-way-to-use-the-apple-sf-symbols-on-the-web

Surprisingly we can render SF Symbol **on the Chrome but not on Safari**. But the former is against SF Symbol's License.(Which only allowed to use on Apple Platform)

You can open this link in Chrome and Safari to see the result. https://jsfiddle.net/4so0wzdk/#

**Comment by parkleo121212** [comment]
> https://stackoverflow.com/questions/64083993/is-there-a-way-to-use-the-apple-sf-symbols-on-the-web
> 
> Surprisingly we can render SF Symbol **on the Chrome but not on Safari**. But the former is against SF Symbol's License.(Which only allowed to use on Apple Platform)
> 
> You can open this link in Chrome and Safari to see the result. https://jsfiddle.net/4so0wzdk/#

Oh... I got it! Than maybe 🗘(U+1F5D8) or 🔄(U+1F504) will fit it. I couldn't find better one : (
And the name of the extension are showed as 'videospeed', and I think it would be better to be the whole name with capital letter. And if it's possible, I want the setting screen to be darker on system dark mode. Thanks a lot! 
![A05E576E-E614-4690-847A-CE757BFA39DD](https://user-images.githubusercontent.com/72724576/135761357-91d7f00c-256d-445a-9216-76bf8c2c7937.jpeg)
![858A964C-50B2-4B7F-9F3B-22A64CEFF85B](https://user-images.githubusercontent.com/72724576/135761364-825b6adf-d719-47cd-b395-41230bbc1302.png)

**Comment by Kyle-Ye** [comment]
> > https://stackoverflow.com/questions/64083993/is-there-a-way-to-use-the-apple-sf-symbols-on-the-web
> > Surprisingly we can render SF Symbol **on the Chrome but not on Safari**. But the former is against SF Symbol's License.(Which only allowed to use on Apple Platform)
> > You can open this link in Chrome and Safari to see the result. https://jsfiddle.net/4so0wzdk/#
> 
> Oh... I got it! Than maybe 🗘(U+1F5D8) or 🔄(U+1F504) will fit it. I couldn't find better one : ( And the name of the extension are showed as 'videospeed', and I think it would be better to be the whole name with capital letter. And if it's possible, I want the setting screen to be darker on system dark mode. Thanks a lot! ![A05E576E-E614-4690-847A-CE757BFA39DD](https://user-images.githubusercontent.com/72724576/135761357-91d7f00c-256d-445a-9216-76bf8c2c7937.jpeg) ![858A964C-50B2-4B7F-9F3B-22A64CEFF85B](https://user-images.githubusercontent.com/72724576/135761364-825b6adf-d719-47cd-b395-41230bbc1302.png)

Got it. Will fix them in the next build. Thank you for your feedback.

**Comment by Kyle-Ye** [comment]
In build 3:
"""
Add a new button with current preferred speed number as text. 
Add dark mode support for the popup windows.
Fix short name to proper capital.
"""
Submit successfully, waiting for Apple to approve.

**Comment by parkleo121212** [comment]
> In build 3: """ Add a new button with current preferred speed number as text. Add dark mode support for the popup windows. Fix short name to proper capital. """
> 
> <img alt="截屏2021-10-06 17 42 34" width="211" src="https://user-images.githubusercontent.com/43724855/136179337-e55f282c-bc03-4982-abf8-49ef0721e3f4.png">
> 
> <img alt="截屏2021-10-06 17 42 27" width="365" src="https://user-images.githubusercontent.com/43724855/136179347-ef7d0863-f189-4ad2-a368-d760b60b3148.png">
> 
> <img alt="截屏2021-10-06 17 37 20" width="185" src="https://user-images.githubusercontent.com/43724855/136179352-5ef10c1e-fbc3-4f9f-bfe5-de98ce5b0b4a.png">

I got that update! Huge thanks for your hard work!
And one more, Could you please increase the number of people who can participate in the beta? Thanks!



https://user-images.githubusercontent.com/72724576/136191768-8a0e199a-4d2c-4cdb-a665-18a41bab23ed.mov

And the video above is the bug i have experiencing. GIF stop when it accelerated more than 2 times.
Also, the controller doesn't show up on youtube.com both mobile version and desktop version of it. Thanks!

**Comment by Kyle-Ye** [comment]
> > In build 3: """ Add a new button with current preferred speed number as text. Add dark mode support for the popup windows. Fix short name to proper capital. """
> > <img alt="截屏2021-10-06 17 42 34" width="211" src="https://user-images.githubusercontent.com/43724855/136179337-e55f282c-bc03-4982-abf8-49ef0721e3f4.png">
> > <img alt="截屏2021-10-06 17 42 27" width="365" src="https://user-images.githubusercontent.com/43724855/136179347-ef7d0863-f189-4ad2-a368-d760b60b3148.png">
> > <img alt="截屏2021-10-06 17 37 20" width="185" src="https://user-images.githubusercontent.com/43724855/136179352-5ef10c1e-fbc3-4f9f-bfe5-de98ce5b0b4a.png">
> 
> I got that update! Huge thanks for your hard work! And one more, Could you please increase the number of people who can participate in the beta? Thanks!
> 
>  RPReplay_Final1633518293.mov 
> 
> And the video above is the bug i have experiencing. GIF stop when it accelerated more than 2 times. Also, the controller doesn't show up on youtube.com both mobile version and desktop version of it. Thanks!

1. Update the beta number to 10000 today
2. GIF may not be a main focus of the extension, and I'm trying to figure the core of the extension. Maybe you could file a bug in the original Chrome extension repository.
3. I try to reproduce your bug again on many youtube videos both on my Mac, iPhone and iPad, they all seem working properly. Could you please add more info in a bug report issue about it? (Like which video you can reproduce this bug)
